### ISSUE TITLE
Token is invalid

### ISSUE THREAD

**Issue by timot7782** [prismagraphql/http-link-dataloader#10]
```
Error: Your token is invalid. It might have expired or you might be using a token from a different project.
    at BatchedGraphQLClient.<anonymous> (E:\POS\hex_pos\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:70:35)
    at step (E:\POS\hex_pos\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:40:23)
    at Object.next (E:\POS\hex_pos\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:21:53)
    at fulfilled (E:\POS\hex_pos\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
it seems that it assigns the header automatically....

**Comment by timot7782** [comment]
Forgot to update the endpoint to point to the latest service in prisma.yml
